name: upcoastv-env
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3
  - biopython=1.74
  - libxcb
  - pandas=1.2.4
  - bwa=0.7.17
  - samtools=1.10
  - bcftools=1.10
  - trim-galore=0.6.5
  - pyvcf=0.6.8
  - pyyaml=5.3.1
  - pysam=0.16.0
  - csvtk=0.22.0
  - graphviz=2.40.1
  - fastqc=0.11.7
  - shovill=1.1.0
  - multiqc=1.9
