Bootstrap: docker
From: continuumio/miniconda3:4.9.2
Stage: condabuild

%labels
authors="Zohaib Anwar"
description="Docker image containing all requirements for the upcoast-v project's vibrio pipeline"

%post
/opt/conda/bin/conda install mamba -c conda-forge && \
/opt/conda/bin/mamba create --name nf-upcoastv-env \
    python=3 biopython=1.74 \
    libxcb pandas=0.23.0=py36_1 \
    bwa=0.7.17=pl5.22.0_2 samtools=1.10 \
    bcftools=1.10 trim-galore=0.6.5 \
    pyvcf=0.6.8 pyyaml=5.3.1 pysam=0.16.0 \
    csvtk=0.22.0 graphviz=2.40.1 fastqc=0.11.7 \
    shovill=1.1.0 multiqc=1.9


Bootstrap: docker
From: debian:buster-slim
Stage: final

%post
apt-get update && \
apt-get install -y git procps && \
apt-get clean -y

%files from condabuild
  /opt/conda/envs/nf-upcoastv-env /opt/conda/envs/nf-upcoastv-env

%environment
export PATH=/opt/conda/envs/nf-upcoastv-env/bin:$PATH
